### ISSUE TITLE
Obtain logs from crowd-in

### ISSUE THREAD

**Issue by winstondu** [crowdin/mobile-sdk-ios#125]
**Is your feature request related to a problem? Please describe.**
For our code, we have a central logging service that sends logs to our server. We would like to keep that consolidated with our server.

**Describe the solution you'd like**
Add a callback whenever CrowdIn logs something (This would probably be via the `CrowdinLogsCollector`.) The iOS client can then set this callback and we can get those logs into our logging service.

**Describe alternatives you've considered**
We are considering making a fork of the SDK to support this.

**Comment by NazarYavornytskyy** [comment]
@winstondu we provide a log callback functionality for next version of SDK, it looks like this:
CrowdinSDK.setOnLogCallback { logMessage in
            print("LOG MESSAGE - \(logMessage)")
        }

Hope it will work for you, please confirm, thanks
