### ISSUE TITLE
When app is in source language and debugger is attached, strings are displayed in caps

### ISSUE THREAD

**Issue by winstondu** [crowdin/mobile-sdk-ios#126]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8174310/113073202-89933e80-917d-11eb-8436-eed6e9d56a23.png)
Normally, when `bundle.localizedString()` fails to find the value for the key, **it returns the key**. However, when localization debugging is turned on and the app is run in debug, **it returns the capitalized version of the key.**

This is an issue, because this means when the app is run with the debugger, the check in this line (https://github.com/crowdin/mobile-sdk-ios/blob/6c4509bf222c599fdf6e5861e955d364a66a2cbe/CrowdinSDK/Classes/CrowdinSDK/Localization/Provider/LocalizationProvider.swift#L152) fails since the string returned is the uppercased version of the key, rather than the key itself. So the equality check fails, and rather than returning `nil` we return the uppercased key. 

**To Reproduce**
With a CrowdIn project in English, run an app on a real device with the XCode debugger (and localization debugging turned on) and the device language set to English. You will see strings in CAPS. 

**Expected behavior**
Display the actual value of that key, rather than displaying the key in uppercase.

**Additional context**
It is interesting that the `localizationProvider` will always fail to find a string when in the source language here [in this line](https://github.com/crowdin/mobile-sdk-ios/blob/6c4509bf222c599fdf6e5861e955d364a66a2cbe/CrowdinSDK/Classes/CrowdinSDK/Localization/Provider/LocalizationProvider.swift#L150): the downloaded `en.plist` is always just empty (I presume this is because it is the CrowdIn project's source language!) Our preferred fix is just to have the `en.plist` not be empty (i.e. always download the en.plist).

We do want to keep localization debugging enabled for our app in XCode.

**Comment by BozhenaDobrovolska** [comment]
Hi Winston! Thank you for the report!
I will pass it on to our devs and will keep you posted

**Comment by serhii-londar** [comment]
Hi @winstondu ! Sorry for delay. We've tried to reproduce your issue. In debug mode SDK shows unlocalised strings capitalised not uppercased, so we're not fully understand what is the issue. Please provide some more details about it. Also, can you reproduce the issue in our example project?

**Comment by winstondu** [comment]
@serhii-londar , could you explain what isn't clear? 

The proposed fix is that CrowdIn actually downloads the source language `plist` file if it isn't in the project.

**Comment by serhii-londar** [comment]
@winstondu Could you describe the issue with steps and your project settings on Crowdin?
