### ISSUE TITLE
CrowdinSDK uses the unencrypted 'http' protocol

### ISSUE THREAD

**Issue by d4r1091** [crowdin/mobile-sdk-ios#141]
**Describe the bug**

```
[!] 'CrowdinSDK' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.
```

**To Reproduce**
1. On your project, run `pod update --repo-update`
2. Observe the issue

**Expected behavior**

Shouldn't happen

**Smartphone (please complete the following information):**
- macOS terminal

**Comment by Olena1234** [comment]
Hello! Thank you for the report, we will check it with devs and come back to you

**Comment by serhii-londar** [comment]
@d4r1091 Hi, a fix for the issue is provided. Please try the new version 1.2.3.
