### ISSUE TITLE
Crash on startup at LocalLocalizationExtractor.localizedString(for:)

### ISSUE THREAD

**Issue by samchanLLM** [crowdin/mobile-sdk-ios#150]
**Describe the bug**
After we turned the Crowdin OTA feature on our apps, we have seen quite a number of crashes on Firebase, all pointing to LocalLocalizationExtractor.localizedString(for:), which is a file in CrowdinSDK

For example here
![Screenshot 2021-11-10 at 11 36 32 AM](https://user-images.githubusercontent.com/94030425/141045359-ec3d398e-73c0-445f-8868-3dec6bb416ac.png)

**To Reproduce**
* We weren't able to reproduce on our side.
* Since Firebase reported 88% of the crash events was happened in the first 5 seconds of a user's session, we suspect it was during the app launch.
* This crash did not happen until we turned the Crowdin OTA feature on.

**Expected behavior**
Should not crash on the SDK side.

**Screenshots**
Code for setting up the Crowdin, it will be called in didFinishLaunchingWithOptions in AppDelegate
![Screenshot 2021-11-10 at 11 49 59 AM](https://user-images.githubusercontent.com/94030425/141046552-d0bffc10-96a8-4331-b28e-f9ab9c7e0383.png)

**Additional context**
We would like to know why this crash will happen, and how to fix it, so we can use this SDK in our production app.

**Comment by Olena1234** [comment]
Hello! Thanks, checking

**Comment by andrii-bodnar** [comment]
Hi @samchanLLM!
Could you please share the full SDK initialization part (in the *AppDelegate.swift* file) and your distribution hash? It will be better to share this data using the [contact form](https://crowdin.com/contacts) with mention of this issue.

**Comment by samchanLLM** [comment]
> Hi @samchanLLM! Could you please share the full SDK initialization part (in the _AppDelegate.swift_ file) and your distribution hash? It will be better to share this data using the [contact form](https://crowdin.com/contacts) with mention of this issue.

just sent, thanks!

**Comment by Rommka4** [comment]
Hi @samchanLLM !

Thank you, we have received your message with the attached file! 

We will let you know as soon as there are updates!

**Comment by samchanLLM** [comment]
Hello, I want to update my description here. I did reproduce the crash I mentioned, and it seems it was due to Crowdin SDK try to get the localized string even if I didn't use NSLocalizedString function, one of the example was it crash when trying to display my username (which does not exist in the String file obviously)

Hope it helps!

**Comment by ira-sem** [comment]
Hi @samchanLLM ! replied in the email where you previously shared the file with us

**Comment by samchanLLM** [comment]
Hello, may I know are there any updates?

**Comment by ira-sem** [comment]
Hi Sam! Sorry for the delay! Will ask the developers for the update and reach you back

**Comment by andrii-bodnar** [comment]
Can't reproduce
