### ISSUE TITLE
iOS xib file translations

### ISSUE THREAD

**Issue by Anton-Oliinyk** [crowdin/mobile-sdk-ios#151]
We have a project that use Crowdin SDK translations, today we found out that .xib files not updating if you did release with updated translations on the crowding website. We got old translations in .xliff file on fresh app install and if update something on the website and release it will not be sent to the app. With .strings files, everything works perfectly fine.

A project that will use .xliff file translations
Start the app and then update translations on crowdin website
Check if new translations are populated on .xib files

**Expected behavior**
.xliff translations work like the .strings ones

If you need any additional data I will answer your questions in comments

**Comment by nataliacrowdin** [comment]
Hi Anton! Let me check everything on our side. We will keep you update on the matter

**Comment by d4r1091** [comment]
Hello @nataliacrowdin 👋 , is there any update on this? Thanks very much for the support

**Comment by Rommka4** [comment]
Hi Dario @d4r1091👋
Sorry for the delay, but I haven't received any updates yet😬
We will be sure to let you know as soon as we receive updates or need additional information

**Comment by andrii-bodnar** [comment]
Hi @Anton-Oliinyk!

We are planning to release this fix soon (waiting for another PR merge before the new version released)

For now, you can try it in the following way:

```
.package(url: "https://github.com/crowdin/mobile-sdk-ios.git", .branch("master"))
```

Also, we will be grateful for the feedback :)
