### ISSUE TITLE
Adding tvOS support

### ISSUE THREAD

**Issue by chrispomeroyhale** [crowdin/mobile-sdk-ios#152]
My team is exploring integrating this SDK for Over-the-Air support to help reduce the releases we need to make just for translations. Our code base is shared between iOS and tvOS which may defeat the purpose if Over-the-Air isn't supported on one platform. Is there a timeline for providing tvOS support?

**Comment by tattiza** [comment]
Hi!
We're planning to investigate this deeply in the near future, but I can't provide an ETA at the moment, as we're working on implementation of swift package manager
