### ISSUE TITLE
Real time preview not working

### ISSUE THREAD

**Issue by stevi-clue** [crowdin/mobile-sdk-ios#159]
Hello!

I am trying to get the real-time preview working on iOS. 

So far I was able to successfully log in and turn the "Real-time" setting to on, however when I type something in the Crowdin editor, the translation is not shown on the device. It also does not work when I click on "Reload translations". The only way this is reflected in the device is when I save the translation and I release the distribution. Do you know if I am missing some step?

Thank you beforehand!

**Comment by ira-sem** [comment]
Hi @stevi-clue ! Could you please also let us know the project name?

**Comment by stevi-clue** [comment]
Thank you for your help! Even though this did not work for the project that I am working on, it worked for the sample project (applereminders) with the same settings, however the real-time preview did not kick in immediately. After a couple of killing and launching the app again, it started working.

**Comment by ira-sem** [comment]
Could you please confirm that you followed all the steps from the instructions? also, can you check the following:
-> the same resource files are uploaded to Crowdin as you have in the application. 
-> the application should have the same language chose as you choose in the Crowdin editor  
-> you should be logged in with the same user
