### ISSUE TITLE
SPM starscream dependency should use latest version 4.0.4

### ISSUE THREAD

**Issue by alexookah** [crowdin/mobile-sdk-ios#167]
Trying to use the crowdinSDK SPM, I noticed that
https://github.com/crowdin/mobile-sdk-ios/blob/master/Package.swift has dependency on Starscrem.

Starscream should be used with the latest version which is 4.0.4:
https://github.com/daltoniam/Starscream/releases/tag/4.0.4

I already use Starscream with version 4.0.4 and can't import crowdinSDK because Starscream dependency uses an older version.

**Comment by serhii-londar** [comment]
Fixed in 1.4.1
