### ISSUE TITLE
Stopping the CrowdinSDK

### ISSUE THREAD

**Issue by alexookah** [crowdin/mobile-sdk-ios#176]
I want to add a settings button in our app to enable/disable the SDK.
Calling CrowdinSDK.stop() does not remove the hover button.

Is this a bug? or is there another way to stop the startedSDK ?

**Comment by andrii-bodnar** [comment]
@serhii-londar do we have the ability to stop the SDK?

**Comment by serhii-londar** [comment]
@andrii-bodnar Yes, the method mentioned above. We just stop the translation related functionality. Additional work needed to stop all the rest features.
