### ISSUE TITLE
watchOS comparability issue 

### ISSUE THREAD

**Issue by Radzievskyi** [crowdin/mobile-sdk-ios#185]
**Describe the bug**

**To Reproduce**
1. Create watchOS project
2. Add CrowdinSDK with Swift Package: https://github.com/crowdin/mobile-sdk-ios.git
3. In the WatchKit Extension module open: 
   **Build Phases -> Link Binary With Libraries** 
and add CrowdinSDK
4. Open **ExtensionDelegate.swift** and add 
`import CrowdinSDK`
5. Try build project for launch on Apple Watch or Apple Watch Simulator
6. You will see 2 errors in **LoginFeature.swift** (from CrowdinSDK) on line:
`import SafariServices`
Error:
**_No such module 'SafariServices'_**
and:
**_SafariServices is not available when building for watchOS Simulator. Consider using `#if !os(watchOS)` to conditionally import this framework._**

**Screenshots**
<img width="550" alt="Screen Shot 2022-04-18 at 13 08 27" src="https://user-images.githubusercontent.com/9761780/163793471-2a6f5586-edf5-439e-9185-1e6279cab2a2.png">

**Smartphone (please complete the following information):**
 - Device: Simulator Apple Watch Series 7
 - OS: watchOS 8.3

**Comment by vance-od** [comment]
hi team 
what are the next steps here? How can we understand when this can be fixed?

This problem is blocking us from fully switching to Crowdin as a source of localization, as our application has to work on both iOS and watchOS

**Comment by ira-sem** [comment]
@vance-od replied via email
As soon as we will have any updates, we will let you know immediately

**Comment by serhii-londar** [comment]
@Radzievskyi Hi. Can you try to integrate SDK from "#185" branch? watchOS support should be fixed.

```
.package(url: "https://github.com/daltoniam/Starscream.git", .branch("#185"))
```

**Comment by Radzievskyi** [comment]
@serhii-londar Hello! Thank you for your update!

Unfortunately I have an issue with launch application with integrated branch “#185”.

For test it.

1. I created a new project for iOS with Swift
2. I added Swift package:
![Screen-Shot-2022-05-11-at-10 42 20](https://user-images.githubusercontent.com/9761780/167800890-95a17ab2-b07b-4d2d-9898-be9d9571785c.jpg)

3. Added to AppDelegate.swift simple initialize Crowdin SDK code, and I get 2 errors:
![Screen-Shot-2022-05-11-at-10 45 10](https://user-images.githubusercontent.com/9761780/167801041-cb381996-cc1d-4e15-b624-200d127210b4.jpg)

Please help me fix this problem.

**Comment by serhii-londar** [comment]
@Radzievskyi The reason is that SDK for watchOS doesn't support login and related features(screenshots and real-time updates), it supports only content delivery feature.
We will note that in Readme. 
Please try the following initialisation:
```
let crowdinProviderConfig = CrowdinProviderConfig(hashString: distributionHash,
                                                          sourceLanguage: sourceLanguage)
let crowdinSDKConfig = CrowdinSDKConfig.config().with(crowdinProviderConfig: crowdinProviderConfig)
CrowdinSDK.startWithConfig(crowdinSDKConfig, completion: { })
```

**Comment by serhii-londar** [comment]
@Radzievskyi Any updates?

**Comment by Radzievskyi** [comment]
@serhii-londar I integrated SDK to the main project. Is work. Thank you!

What we should do next? Use branch #185 or you will merge it with main?

**Comment by serhii-londar** [comment]
@Radzievskyi Thank you for the testing! We will merge it to master and prepare a new release.
