### ISSUE TITLE
SPM 1.4.2 version not working

### ISSUE THREAD

**Issue by alexookah** [crowdin/mobile-sdk-ios#194]
`Cannot find 'CrowdinLoginConfig' in scope`

The last update does not work with SPM. try to run with SPM before releasing a new version.

**Comment by andrii-bodnar** [comment]
@serhii-londar

**Comment by andrii-bodnar** [comment]
Hi @alexookah!

Is there any more detailed backtrace?

**Comment by andrii-bodnar** [comment]
Hi @alexookah!

Currently, Crowdin SDK for SPM supports only the Content Delivery feature. We are working on adding the Screenshots and Real-Time Preview features support for the SPM package.

**Comment by Sam0711er** [comment]
Hey there! @andrii-bodnar What's the current status/timeline of adding the Live Preview Capabilities to SPM?

Greetings from Berlin 🙏

**Comment by andrii-bodnar** [comment]
Hi @Sam0711er!

Currently, we are working on this. It requires a lot of structural changes and refactoring.

Sorry for the inconvenience!

**Comment by serhii-londar** [comment]
@Sam0711er What platforms do you need support for?

**Comment by Sam0711er** [comment]
@serhii-londar Our application runs native on iOS/iPadOS and also on macOS using Mac Catalyst (Universal)

**Comment by Sam0711er** [comment]
Hi @andrii-bodnar @serhii-londar! Just checking to see how y'all are moving along with Support for SPM for the Live Preview Capabilities. Can you already share a rough estimate on when the necessary changes have been performed? Thx!

**Comment by andrii-bodnar** [comment]
@alexookah we merged this PR but haven't released the new version yet

**Comment by alexookah** [comment]
then maybe this ticket should not have close until it's released and ready to use

**Comment by andrii-bodnar** [comment]
@alexookah available in [1.5.0](https://github.com/crowdin/mobile-sdk-ios/releases/tag/1.5.0)
