### ISSUE TITLE
Make API calls to the `api.crowdin.com` instead of `crowdin.com`

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/mobile-sdk-ios#203]
Calls to the Crowdin API should be invoked to the `https://api.crowdin.com` (crowdin.com) and `https://{organization_domain}.api.crowdin.com` (Crowdin Enterprise) base URLs.

There are a few files where the API base URL should be updated:

- [CrowdinAPI.swift](https://github.com/crowdin/mobile-sdk-ios/blob/c91b16912d14f628c69672d3a9f3a3e18a12f632/Sources/CrowdinSDK/CrowdinAPI/CrowdinAPI.swift)
- [DistributionsAPITests.swift](https://github.com/crowdin/mobile-sdk-ios/blob/96660c69ec82a7b25c2a0882056a630a49af39bd/Sources/Tests/CrowdinAPI/DistributionsAPITests.swift)
- [CrowdinAPITests.swift](https://github.com/crowdin/mobile-sdk-ios/blob/9f62080efa969ad56db94698d83607fbd6e5a1e8/Sources/Tests/CrowdinAPI/CrowdinAPITests.swift)
- [ProjectsAPITests.swift](https://github.com/crowdin/mobile-sdk-ios/blob/96660c69ec82a7b25c2a0882056a630a49af39bd/Sources/Tests/CrowdinAPI/ProjectsAPITests.swift)
- [LanguagesAPITests.swift](https://github.com/crowdin/mobile-sdk-ios/blob/96660c69ec82a7b25c2a0882056a630a49af39bd/Sources/Tests/CrowdinAPI/LanguagesAPITests.swift)

API Reference:
- [crowdin.com](https://developer.crowdin.com/api/v2/#section/Introduction/Requests)
- [Crowdin Enterprise](https://developer.crowdin.com/enterprise/api/v2/#section/Introduction/Requests)

**Comment by manish-singh-bisht** [comment]
Hey @andrii-bodnar  I am interested in doing this, please assign me this.
