### ISSUE TITLE
Cannot find 'ScreenshotFeature' in scope 

### ISSUE THREAD

**Issue by edvinass** [crowdin/mobile-sdk-ios#208]
**Describe the bug**
Cannot find 'ScreenshotFeature' in scope 
SDK 1.5.0 version, using swift package manager in Xcode 14.0

Tried regular troubleshooting steps:
- to clean the build 
- remove derived data 
Still no luck.

**To Reproduce**
1. Add crowding SDK swift package into project
2. import SwiftUI
3. try to access ScreenshotFeature.shared 
4. Cannot find 'ScreenshotFeature' in scope

**Expected behavior**
if imported CrowdinSDK it should be in scope.
Can access all other CrowdinSDK classes in the same swift file.

**Screenshots**
<img width="1135" alt="Screenshot 2022-11-03 at 09 06 36" src="https://user-images.githubusercontent.com/60510384/199682639-6a9242c2-7169-4562-ac8f-89594c0f0704.png">

**Additional info**
<img width="709" alt="Screenshot 2022-11-03 at 09 10 39" src="https://user-images.githubusercontent.com/60510384/199683430-ff132f50-266c-4d54-a045-f6a806ba56d5.png">

<img width="542" alt="Screenshot 2022-11-03 at 09 07 54" src="https://user-images.githubusercontent.com/60510384/199682865-8cc334ac-ae7c-4373-a299-0021dea6142e.png">

**Comment by serhii-londar** [comment]
@edvinass Unfortunately ScreenshotFeature is SDK internal class. you don't have to use it. Instead, you should use static methods of CrowdinSDK class:
```
CrowdinSDK.captureScreenshot(name: String(Date().timeIntervalSince1970)) {
    print("Success")
} errorHandler: { error in
    print(error?.localizedDescription)
}
``` 

I see that we have added an incorrect guide to our readme file :( Sorry for the inconvenience!

**Comment by edvinass** [comment]
I see. Thank you for the help!!!
