### ISSUE TITLE
SDK with SwiftUI does not seem to do much?

### ISSUE THREAD

**Issue by edvinass** [crowdin/mobile-sdk-ios#210]
**Describe the bug**
I am not sure if this is a bug or you just don't support SwiftUI.
I was under assumption if you make screenshot all the strings should be taged in them automatically, 
but only got can see string from UIKit context. 

**Additional context**
Is this a bug? If not are you planning to add SwiftUI support any time soon?
Thanks!

**Comment by andrii-bodnar** [comment]
Hi @edvinass,

The SwiftUI support is a bit limited now due to technical reasons. Have you seen the [SwiftUI support](https://github.com/crowdin/mobile-sdk-ios#swiftui-support) section in the Readme? Is it helpful for you or not?

Anyway, thanks for the request!
