### ISSUE TITLE
Internal error after login

### ISSUE THREAD

**Issue by guillaumeramey** [crowdin/mobile-sdk-ios#217]
Hello,
I want to use the screenshot functionality in my app but I encounter an internal server error when I try to login to my Crowdin account on both simulator & physical device.

Edit: I also get this the first time I try to login:
`{"redirect_to":"\/oauth\/authorize?client_id=xxx&response_type=code&scope=project.screenshot&redirect_uri=crowdintest%3A%2F%2F&domain=xxx&intended=%2Foauth%2Fauthorize%3Fclient_id%3Dxxx%26response_type%3Dcode%26scope%3Dproject.screenshot%26redirect_uri%3Dcrowdintest%253A%252F%252F","method":"GET"}`
(xxx hides personal data)

![popup](https://user-images.githubusercontent.com/43143518/223686180-7f0d71a4-4b50-45f6-b9d1-16eb5948e346.png)
![server error](https://user-images.githubusercontent.com/43143518/223686188-697f73f4-4fa3-4d40-a573-cd4c87101164.png)

**Comment by andrii-bodnar** [comment]
Hi @guillaumeramey, could you please provide your Crowdin SDK config and also check if the issue is reproducible on our example project? Thanks.

**Comment by andrii-bodnar** [comment]
@guillaumeramey probably there is something with your `loginConfig`. Could you please share it using [this contact form](https://crowdin.com/contacts)? Also, we'd appreciate it if you can record a video demonstrating the authorization process via Crowdin SDK. Thank you.

**Comment by guillaumeramey** [comment]
Hi Andrii, 
I changed the scope to “project”.

We already have a custom URL scheme in our app as you can see in the screenshot.

￼

I can’t find any Crowdin OAuth configuration though.

**Comment by andrii-bodnar** [comment]
@guillaumeramey our QA team just tried to reproduce this issue on the [Example project](https://github.com/crowdin/mobile-sdk-ios/tree/master/Example) and everything works great, we can't reproduce it.

Could you please share your environment details and some steps to reproduce? Thanks.

**Comment by guillaumeramey** [comment]
@andrii-bodnar I sent you a simple project in which I import crowdin SDK and it's not working either. Maybe I am doing something wrong ? We are using an enterprise account, I am also not sure if I have all the required rights.

**Comment by andrii-bodnar** [comment]
Hi @guillaumeramey thanks a lot for the sample project, we've already passed it to our QA team. I'll additionally clarify the status with them and will come back to you if we need additional details

**Comment by guillaumeramey** [comment]
Hi @andrii-bodnar , I now have admin privileges on my organization so I can access the OAuth apps settings.
I also hava a new screen appearing just after I chose "Keep me logged in":
![Simulator Screen Shot - iPhone 14 - 2023-03-15 at 17 51 19](https://user-images.githubusercontent.com/43143518/225383619-11d67cb5-e034-4b43-a41e-3152ba5a90db.png)

However nothing happens when I tap on any of the buttons at the bottom.

**Comment by andrii-bodnar** [comment]
Couldn't reproduce, needs [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)
