### ISSUE TITLE
Switch must be exhaustive in SocketAPI (StarScream 4.0.6 update)

### ISSUE THREAD

**Issue by phiilu** [crowdin/mobile-sdk-ios#226]
**Describe the bug**
StarScream released a new version (4.0.6) where the added a new enum and now the project won't be able to compile. 

**To Reproduce**
1. Use the latest Package versions (Xcode -> File -> Packages -> Update To Latest Package Version)
2. Try building your project

**Expected behavior**
The project compiles without errors

**Screenshots**
![image](https://github.com/crowdin/mobile-sdk-ios/assets/8149519/307653fd-18fe-4da7-8b46-6dd59c31fdde)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 16

**Additional context**
There is already a Bug ticket on StarScream: https://github.com/daltoniam/Starscream/issues/975

The changed code should be here: https://github.com/crowdin/mobile-sdk-ios/blob/b7c11e3a1a64dc12051455df8c722804105348aa/Sources/CrowdinSDK/Features/RealtimeUpdateFeature/SocketAPI/SocketAPI.swift#L82-L105 

Related PR that fix this: https://github.com/crowdin/mobile-sdk-ios/pull/225

**Comment by serhii-londar** [comment]
Work in progress in #225

**Comment by guidev** [comment]
is there a fix yet?

**Comment by andrii-bodnar** [comment]
https://github.com/crowdin/mobile-sdk-ios/releases/tag/1.6.0
