### ISSUE TITLE
Languages with dialects aren't downloading

### ISSUE THREAD

**Issue by serejaonly** [crowdin/mobile-sdk-ios#227]
**Describe the bug**
Languages with dialects (`pt-BR`) aren't downloading (it might be only for Crowdin Enterprise)

**To Reproduce**
1. Set `pt-BR` language in the app
2. Start the app
3. See that strings aren't downloaded

**Expected behavior**
Expected to download it as different languages

**Screenshots**
<img width="414" alt="image" src="https://github.com/crowdin/mobile-sdk-ios/assets/33960459/06bebd89-6e16-4daa-b54f-dde3f6569219">

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.4

**Additional context**
Languages with dialects are denoted with a hyphen (pt-BR), and locales are denoted with an underscore (pt_BR).
There seems to be a confusion of these two concepts in the SDK at the stage of adding downloadable languages to `CrowdinRemoteLocalisationStorage`.
The final stage where the error occurs is the `ManifestManager.iOSLanguageCode(for:)` method, because it takes the locale code instead of the language code.
```swift
func iOSLanguageCode(for crowdinLocalization: String) -> String? {
    allLanguages.first(where: { $0.id == crowdinLocalization })?.osxLocale
}
```
I think it makes sense to replace the `osxLocale` with `iOSLanguageCode` to fix that.

**Comment by andrii-bodnar** [comment]
Recently we released the [new version](https://github.com/crowdin/mobile-sdk-android/releases/tag/1.8.0) of the Android SDK with the fix for a such situation.

The same thing should be applied here. We should move the `organizationName` to the `CrowdinProviderConfig` level keeping the backward compatibility.

**Comment by andrii-bodnar** [comment]
https://github.com/crowdin/mobile-sdk-ios/releases/tag/1.6.0
