### ISSUE TITLE
WatchOS does not compile in Xcode 15

### ISSUE THREAD

**Issue by laurentaylormarshall** [crowdin/mobile-sdk-ios#229]
**Describe the bug**
The package product 'Starscream' requires minimum platform version 5.0 for the watchOS platform, but this target supports 4.0

**To Reproduce**
Download Xcode 15. Build the package for watchOS.

**Expected behavior**
The framework should build without any errors.

**Screenshots**
![image](https://github.com/crowdin/mobile-sdk-ios/assets/44420971/2989bff5-bc7c-49bc-ac77-212e0c8457d5)

**Smartphone (please complete the following information):**
Xcode 15

**Additional context**
You will need to update the minimum version of support to v5 in the Package file.

**Comment by laurentaylormarshall** [comment]
Great! @andrii-bodnar @serhii-londar do you know when the next release will be?

**Comment by andrii-bodnar** [comment]
Hi @laurentaylormarshall, we'll be releasing a new version about next week.

**Comment by andrii-bodnar** [comment]
https://github.com/crowdin/mobile-sdk-ios/releases/tag/1.6.0
