### ISSUE TITLE
Question: Toast.swift?

### ISSUE THREAD

**Issue by kvaDrug** [crowdin/mobile-sdk-ios#261]
Hi! For what purpose you include Toast.swift (Toast banners UIView extension) by Charles Scalesse to the iOS sdk?

**Comment by serhii-londar** [comment]
Hi, good question. 
For some reason, it's included in core SDK but is used only with a floating menu to notify users about successful login/logout actions.

**Comment by serhii-londar** [comment]
@kvaDrug How do you integrate CrowdinSKD via cocoapods or SPM?

**Comment by andrii-bodnar** [comment]
@serhii-londar can we extract this Toast component from core to the SDK floating menu? Or even replace this toast component with something native instead.

**Comment by andrii-bodnar** [comment]
I think we should remove this component and replace it with a native alternative.

**Comment by kvaDrug** [comment]
Thank you guys for taking actions on my request! The simpler the better. I had some warnings from that lib.
