### ISSUE TITLE
Not working screenshot feature

### ISSUE THREAD

**Issue by PeHk** [crowdin/mobile-sdk-ios#264]
**Describe the bug**
Crowdin Screenshot feature is not working anymore. The implementation worked properly 6 months ago, now we are not able to use it anymore.

**To Reproduce**
1. Open floating settings button and log in with role MANAGER or OWNER
2. In floating settings try to capture screenshot (be aware to have source language of the app same as defined in Crowdin)
3. Nothing happens

**Expected behavior**
The screenshot should or should not be taken with appropriate informative toast (in case of error with error message)

**Screenshots**
<img src="https://github.com/crowdin/mobile-sdk-ios/assets/32091206/839118a0-9f1c-4561-ac9b-3e144421e948" width="200"/>

No error or any other action is logged. Also I cannot open any detail of the logs - just nothing happens.
<img src="https://github.com/crowdin/mobile-sdk-ios/assets/32091206/3120258f-702a-45db-864c-dcb91f204b4c" width="200"/>

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro, iPhone 13 Pro
 - OS: iOS 16.X, iOS 17.X

**Additional context**
After some investigation and research I found that issue is in this definition:

```
func cw_get<T: Decodable>(url: String, parameters: [String: String]? = nil, headers: [String: String]? = nil, completion: @escaping (T?, Error?) -> Swift.Void) {
        self.get(url: url, parameters: parameters, headers: addDefaultHeaders(to: headers), completion: { data, response, error in
            if self.isUnautorized(response: response) {
                NotificationCenter.default.post(name: .CrowdinAPIUnautorizedNotification, object: nil)
                return;
            }
            guard let data = data else {
                completion(nil, error)
                return
            }
            
            CrowdinAPILog.logRequest(method: RequestMethod.GET.rawValue, url: url, parameters: parameters, headers: self.addDefaultHeaders(to: headers), responseData: data)
            
            do {
                let response = try JSONDecoder().decode(T.self, from: data)
                completion(response, error)
            } catch {
                print(String(data: data, encoding: .utf8) ?? "Data is empty")
                completion(nil, error)
            }
        })
    }
```

in more detail in this few rows (the completion missing, it should not be just 'return' because than the action is never completed):
```
if self.isUnautorized(response: response) {
                NotificationCenter.default.post(name: .CrowdinAPIUnautorizedNotification, object: nil)
                return;
            }
```

I am **logged in**, I have the role of **MANAGER** which is mandatory for creating a screenshot, I have same source language in app as defined in Crowdin, **I am able to use other features** (OTA updates) but when creating screenshot I am **unauthorized**. **No log message, no refresh or force logout
. Nothing.**

Crowdin SDK is installed through SPM but same behavior is through CocoaPods as well. The version is latest 1.7.0

**Comment by serhii-londar** [comment]
@PeHk Thanks for the report! Please check whether you're passing organization name to CrowdinProvider:

`let crowdinProviderConfig = CrowdinProviderConfig(hashString: distributionHash,
                                                          sourceLanguage: sourceLanguage,
                                                          organizationName: organizationName)`

**Comment by PeHk** [comment]
Hi @serhii-londar, thank you for your suggestion. It seems that it solved the problem which brings me to your official documentation (accessible directly in the "Tools" tab of my enterprise account) where is this:

```
let crowdinSDKConfig = CrowdinProviderConfig(hashString: "{your_distribution_hash}",
             sourceLanguage: "en") // project source language 
          
CrowdinSDK.startWithConfig(crowdinSDKConfig, completion: {
    // SDK is ready to use, put code to change language, etc. here
})
```

There is no information about `organizationName`. When I open Advanced features (for Screenshot) there is `CrowdinLoginConfig` where is such an attribute `organizationName` but it's **deprecated**, not safe to use and the attribute is optional. 

I think this information should be more visible in documentation, also for enterprise users it should be **required** and not optional. Additional suggestion is to have some toast with error code for unauthorized requests and not just `return;` without completion. It may help in the future because in case of our problem we lost a lot of time communicating with Crowdin support without success. 

Thanks!

**Comment by serhii-londar** [comment]
@andrii-bodnar I've added fix for adding logs when receiving unauthorized requests. 
Can we update documentation for enterprise users? Looks like template still have example with passing organization name to Login config instead of CrowdinProviderConfig.

**Comment by andrii-bodnar** [comment]
@serhii-londar yes, the documentation will be updated.
