### ISSUE TITLE
Starscream version

### ISSUE THREAD

**Issue by carayolthomas** [crowdin/mobile-sdk-ios#61]
**Is your feature request related to a problem? Please describe.**
I am trying to add your SDK in an iOS app which depends on the latest `Starscream` version `3.1.1`. However your SDK depends on the `3.0.6` version.

**Describe the solution you'd like**
Is it planned to update `Starscream` to `3.1.X`?

**Comment by andrii-bodnar** [comment]
Hi @carayolthomas, thanks a lot for your suggestion. 

Already checking the possibility to update the `Starscream` version.
