### ISSUE TITLE
ld: framework not found BaseAPI

### ISSUE THREAD

**Issue by bzz445** [crowdin/mobile-sdk-ios#93]
**Describe the bug**
For test i created empty projects (objective-c and swift) with one pod CrowdinSDK and when run Build on **Any iOS device** or **Simulator** get this error. For Swift project: `ld: framework not found BaseAPI`. For Objective-c project: `fatal error: module map file '~/Library/Developer/Xcode/DerivedData/Empty-dnjsexrkxdmbmeaeuqkddudleoda/Build/Products/Debug-iphonesimulator/BaseAPI/BaseAPI.modulemap' not found`

When Run or Build on **iPhone** i no have error.

**Environment**
macOS: 10.15.6
Xcode: 12.0.1
CocoaPod: 1.9.3
CrowdinSDK: 1.1.5

**Comment by serhii-londar** [comment]
Hi @bzz445, Thanks for your report. I couldn't reproduce your issue. Could you please share your example project with me?

**Comment by serhii-londar** [comment]
@bzz445 Any updates there?
